### ISSUE TITLE
javax.net.ssl.SSLHandshakeException 加载图片可能会报这个错

### ISSUE THREAD

**Issue by LukeMi** [wildma/okhttps#1]
解决方法参阅 http://blog.csdn.net/u014752325/article/details/73217577 ，题主帮忙完善下多加一个 SSLSocketClient 类， OkHttpGlideModule 对应方法代码如下 ：

 @Override
    public void registerComponents(Context context, Glide glide) {
        OkHttpClient mHttpClient = new OkHttpClient().newBuilder()
                .sslSocketFactory(SSLSocketClient.getSSLSocketFactory())
                .hostnameVerifier(SSLSocketClient.getHostnameVerifier())
                .build();
        glide.register(GlideUrl.class,
                InputStream.class,
                new OkHttpUrlLoader.Factory(mHttpClient));
    }

**Comment by wildma** [comment]
请问你运行我的Demo在什么情况下才会报这个错误呢？ 我测试过多种机型没遇到过这个问题呢
