### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by forever123** [wildma/okhttps#3]
报错信息为：--------------onFailure--------------javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
  是因为 12306更新了证书么？还是什么其他原因

**Comment by wildma** [comment]
可能吧，你直接拿自己项目的证书来测试就知道了。
